apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vjtt5grql-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vjtt5grql-java-quarkus-gitops